### ISSUE TITLE
Make win count mathematical

### ISSUE THREAD

**Issue by aydin41k** [aydin41k/catematics#9]
To add extra spice, win count can be displayed as 10x + y. I.e.:
5 wins --> Wins: 5
10 wins: Wins: 10
12 wins: Wins: 10 + 2
20 wins: Wins: 10 x 2
25 wins: Wins: 10 x 2 + 5
...etc.

But this should be conditional to:
1. Max addend >= 10
2. Multiplications are enabled

**Comment by CoderNamedNick** [comment]
Hey I'm a beginner at JavaScript and I would love to try to help with this problem if possible.!

**Comment by Sabbirfeni** [comment]
Hey Aydin,

Hope you are doing well. I have checked the issue and able to fix it. Please assign the issue to me.

Thanks,
Shabbir

**Comment by Sabbirfeni** [comment]
Thanks, 

I will get down to work as soon as I back to work.

**Comment by aydin41k** [comment]
Much appreciated @Sabbirfeni ! Let me know if you need anything.
